-- The database under ./db is autogenerated. Changing the entries there
-- will result in a data loss whenever a new database gets extracted.
-- To be able to customize and/or fix entries that aren't yet detected
-- by the extractor logic, this file here can be used to save overwrites.

do -- area trigger
end

do -- items
end

do -- units/npcs
end

do -- quests
  -- Add "Dark Iron Gunpowder Keg" to objectives of "Vile Dwarven Pigs"
  -- The extractor scripts did not catch those, as the objetive is filled via a Gossip on use.
  pfDB["quests"]["data-turtle"][41682]["obj"]["O"] = { 2020173 }

  -- Add "Head of Geshgan" to the loot table of "Geshgan"
  -- This can be removed by the next database export
  pfDB["items"]["data-turtle"][41783]["U"] = { [62217] = 1.0 }
end
