-- The database under ./db is autogenerated. Changing the entries there
-- will result in a data loss whenever a new database gets extracted.
-- To be able to customize and/or fix entries that aren't yet detected
-- by the extractor logic, this file here can be used to save overwrites.

-- Highlord Bolvar Fordragon (Stormwind)
pfDB["units"]["data-turtle"][1748] = {
  ["coords"] = {
    [1] = { 80.2, 38.3, 1519, 30 },
  },
  ["fac"] = "A",
  ["lvl"] = "63",
}

-- Lady Katrana Prestor (Stormwind)
pfDB["units"]["data-turtle"][1749] = {
  ["coords"] = {
    [1] = { 80.1, 38.2, 1519, 30 },
  },
  ["fac"] = "A",
  ["lvl"] = "62",
}
